[build]
  base = "./"
  publish = "/app/dist/"
  command = "npm run build:app"
  environment = { NODE_ENV = "development", NODE_VERSION = "14.15.3", DOMAIN = "http://localhost:9000" }
  
  functions = "functions"

[context.master]
  environment = { NODE_ENV = "production", DOMAIN = "https://deniskent.com" }

[dev]
  command = "npm run dev:app"
  port = 9000
  targetPort = 7777
  publish = "/app/dist/" 
  autoLaunch = true
  framework = "#custom"